# Generated by Django 3.0.3 on 2020-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'access_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'accounts_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('email', models.TextField()),
                ('contact_num', models.IntegerField()),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('created_by', models.TextField()),
                ('updated_by', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employees_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('temp_code', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'online_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('access_id', models.IntegerField()),
            ],
            options={
                'db_table': 'roles_info',
                'managed': False,
            },
        ),
    ]
